<?xml version="1.0" encoding="utf-8"?><Database Name="DU_LICH" Class="WEB_DULICHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-JRLFG0U\SQLEXPRESS;Initial Catalog=DU_LICH;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DU_LICHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.KHACH_HANG" Member="KHACH_HANGs">
    <Type Name="KHACH_HANG">
      <Column Name="MA_KH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_KH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NGAY_SINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GIOI_TINH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="PASSPORT" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="MA_QUOC_GIA" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DIA_CHI" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="TAI_KHOAN_KH" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="MAT_KHAU_KH" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="DIEN_THOAI" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="GHI_CHU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="KHACH_HANG_DAT_TOUR" Member="DAT_TOURs" ThisKey="MA_KH" OtherKey="MA_TOUR" Type="DAT_TOUR" />
      <Association Name="QUOC_GIA_KHACH_HANG" Member="QUOC_GIA" ThisKey="MA_QUOC_GIA" OtherKey="MA_QUOC_GIA" Type="QUOC_GIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHI_TIET_TOUR" Member="CHI_TIET_TOURs">
    <Type Name="CHI_TIET_TOUR">
      <Column Name="MA_TOUR" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_DIEM_DL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CHUONG_TRINH_TOUR_CHI_TIET_TOUR" Member="CHUONG_TRINH_TOUR" ThisKey="MA_TOUR" OtherKey="MA_TOUR" Type="CHUONG_TRINH_TOUR" IsForeignKey="true" />
      <Association Name="DIEM_DU_LICH_CHI_TIET_TOUR" Member="DIEM_DU_LICH" ThisKey="MA_DIEM_DL" OtherKey="MA_DIEM_DL" Type="DIEM_DU_LICH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TINH" Member="TINHs">
    <Type Name="TINH">
      <Column Name="MA_TINH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_TINH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MA_MIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TINH_DIEM_DU_LICH" Member="DIEM_DU_LICHes" ThisKey="MA_TINH" OtherKey="MA_TINH" Type="DIEM_DU_LICH" />
      <Association Name="MIEN_TINH" Member="MIEN" ThisKey="MA_MIEN" OtherKey="MA_MIEN" Type="MIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUONG_TRINH_TOUR" Member="CHUONG_TRINH_TOURs">
    <Type Name="CHUONG_TRINH_TOUR">
      <Column Name="MA_TOUR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HINH_ANH" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="TEN_TOUR" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GIA_TOUR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NGAY_KHOI_HANH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAY_KET_THUC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SO_CHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GHI_CHU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="NOI_DUNG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICH_TRINH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CHINH_SACH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CAU_HOI_THUONG_GAP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="CHUONG_TRINH_TOUR_CHI_TIET_TOUR" Member="CHI_TIET_TOURs" ThisKey="MA_TOUR" OtherKey="MA_TOUR" Type="CHI_TIET_TOUR" />
      <Association Name="CHUONG_TRINH_TOUR_DAT_TOUR" Member="DAT_TOURs" ThisKey="MA_TOUR" OtherKey="MA_TOUR" Type="DAT_TOUR" />
    </Type>
  </Table>
  <Table Name="dbo.DAT_TOUR" Member="DAT_TOURs">
    <Type Name="DAT_TOUR">
      <Column Name="MA_DAT_TOUR" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_TOUR" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_KH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIA_NGUOI_LON" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GIA_TRE_EM" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SO_NGAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SO_CHO_DAT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAY_DAT" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PHU_THU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THANH_TIEN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="CHUONG_TRINH_TOUR_DAT_TOUR" Member="CHUONG_TRINH_TOUR" ThisKey="MA_TOUR" OtherKey="MA_TOUR" Type="CHUONG_TRINH_TOUR" IsForeignKey="true" />
      <Association Name="KHACH_HANG_DAT_TOUR" Member="KHACH_HANG" ThisKey="MA_TOUR" OtherKey="MA_KH" Type="KHACH_HANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIEM_DU_LICH" Member="DIEM_DU_LICHes">
    <Type Name="DIEM_DU_LICH">
      <Column Name="MA_DIEM_DL" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HINH_ANH" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="TEN_DIEM_DL" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="THONG_TIN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MA_TINH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DIEM_DU_LICH_CHI_TIET_TOUR" Member="CHI_TIET_TOURs" ThisKey="MA_DIEM_DL" OtherKey="MA_DIEM_DL" Type="CHI_TIET_TOUR" />
      <Association Name="DIEM_DU_LICH_HINH_ANH" Member="HINH_ANHs" ThisKey="MA_DIEM_DL" OtherKey="MA_DIEM_DL" Type="HINH_ANH" />
      <Association Name="TINH_DIEM_DU_LICH" Member="TINH" ThisKey="MA_TINH" OtherKey="MA_TINH" Type="TINH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HINH_ANH" Member="HINH_ANHs">
    <Type Name="HINH_ANH">
      <Column Name="MA_HINH_ANH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_HINH_ANH" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="LINK_HINH_ANH" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="MA_DIEM_DL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DIEM_DU_LICH_HINH_ANH" Member="DIEM_DU_LICH" ThisKey="MA_DIEM_DL" OtherKey="MA_DIEM_DL" Type="DIEM_DU_LICH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MIEN" Member="MIENs">
    <Type Name="MIEN">
      <Column Name="MA_MIEN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_MIEN" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TRONG_NGOAI_NUOC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MIEN_TINH" Member="TINHs" ThisKey="MA_MIEN" OtherKey="MA_MIEN" Type="TINH" />
    </Type>
  </Table>
  <Table Name="dbo.QUAN_TRI_VIEN" Member="QUAN_TRI_VIENs">
    <Type Name="QUAN_TRI_VIEN">
      <Column Name="TAI_KHOAN" Type="System.String" DbType="NChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAT_KHAU" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUOC_GIA" Member="QUOC_GIAs">
    <Type Name="QUOC_GIA">
      <Column Name="MA_QUOC_GIA" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_QUOC_GIA" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GHI_CHU" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="QUOC_GIA_KHACH_HANG" Member="KHACH_HANGs" ThisKey="MA_QUOC_GIA" OtherKey="MA_QUOC_GIA" Type="KHACH_HANG" />
    </Type>
  </Table>
</Database>