#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DU_LICH")]
	public partial class WEB_DULICHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTINH(TINH instance);
    partial void UpdateTINH(TINH instance);
    partial void DeleteTINH(TINH instance);
    partial void InsertCHI_TIET_TOUR(CHI_TIET_TOUR instance);
    partial void UpdateCHI_TIET_TOUR(CHI_TIET_TOUR instance);
    partial void DeleteCHI_TIET_TOUR(CHI_TIET_TOUR instance);
    partial void InsertCHUONG_TRINH_TOUR(CHUONG_TRINH_TOUR instance);
    partial void UpdateCHUONG_TRINH_TOUR(CHUONG_TRINH_TOUR instance);
    partial void DeleteCHUONG_TRINH_TOUR(CHUONG_TRINH_TOUR instance);
    partial void InsertDAT_TOUR(DAT_TOUR instance);
    partial void UpdateDAT_TOUR(DAT_TOUR instance);
    partial void DeleteDAT_TOUR(DAT_TOUR instance);
    partial void InsertDIEM_DU_LICH(DIEM_DU_LICH instance);
    partial void UpdateDIEM_DU_LICH(DIEM_DU_LICH instance);
    partial void DeleteDIEM_DU_LICH(DIEM_DU_LICH instance);
    partial void InsertHINH_ANH(HINH_ANH instance);
    partial void UpdateHINH_ANH(HINH_ANH instance);
    partial void DeleteHINH_ANH(HINH_ANH instance);
    partial void InsertKHACH_HANG(KHACH_HANG instance);
    partial void UpdateKHACH_HANG(KHACH_HANG instance);
    partial void DeleteKHACH_HANG(KHACH_HANG instance);
    partial void InsertLOAI_TOUR(LOAI_TOUR instance);
    partial void UpdateLOAI_TOUR(LOAI_TOUR instance);
    partial void DeleteLOAI_TOUR(LOAI_TOUR instance);
    partial void InsertMIEN(MIEN instance);
    partial void UpdateMIEN(MIEN instance);
    partial void DeleteMIEN(MIEN instance);
    partial void InsertQUAN_TRI_VIEN(QUAN_TRI_VIEN instance);
    partial void UpdateQUAN_TRI_VIEN(QUAN_TRI_VIEN instance);
    partial void DeleteQUAN_TRI_VIEN(QUAN_TRI_VIEN instance);
    partial void InsertQUOC_GIA(QUOC_GIA instance);
    partial void UpdateQUOC_GIA(QUOC_GIA instance);
    partial void DeleteQUOC_GIA(QUOC_GIA instance);
    #endregion
		
		public WEB_DULICHDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DU_LICHConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WEB_DULICHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WEB_DULICHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WEB_DULICHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WEB_DULICHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TINH> TINHs
		{
			get
			{
				return this.GetTable<TINH>();
			}
		}
		
		public System.Data.Linq.Table<CHI_TIET_TOUR> CHI_TIET_TOURs
		{
			get
			{
				return this.GetTable<CHI_TIET_TOUR>();
			}
		}
		
		public System.Data.Linq.Table<CHUONG_TRINH_TOUR> CHUONG_TRINH_TOURs
		{
			get
			{
				return this.GetTable<CHUONG_TRINH_TOUR>();
			}
		}
		
		public System.Data.Linq.Table<DAT_TOUR> DAT_TOURs
		{
			get
			{
				return this.GetTable<DAT_TOUR>();
			}
		}
		
		public System.Data.Linq.Table<DIEM_DU_LICH> DIEM_DU_LICHes
		{
			get
			{
				return this.GetTable<DIEM_DU_LICH>();
			}
		}
		
		public System.Data.Linq.Table<HINH_ANH> HINH_ANHs
		{
			get
			{
				return this.GetTable<HINH_ANH>();
			}
		}
		
		public System.Data.Linq.Table<KHACH_HANG> KHACH_HANGs
		{
			get
			{
				return this.GetTable<KHACH_HANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_TOUR> LOAI_TOURs
		{
			get
			{
				return this.GetTable<LOAI_TOUR>();
			}
		}
		
		public System.Data.Linq.Table<MIEN> MIENs
		{
			get
			{
				return this.GetTable<MIEN>();
			}
		}
		
		public System.Data.Linq.Table<QUAN_TRI_VIEN> QUAN_TRI_VIENs
		{
			get
			{
				return this.GetTable<QUAN_TRI_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<QUOC_GIA> QUOC_GIAs
		{
			get
			{
				return this.GetTable<QUOC_GIA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINH")]
	public partial class TINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_TINH;
		
		private string _TEN_TINH;
		
		private System.Nullable<int> _MA_MIEN;
		
		private EntitySet<DIEM_DU_LICH> _DIEM_DU_LICHes;
		
		private EntityRef<MIEN> _MIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_TINHChanging(int value);
    partial void OnMA_TINHChanged();
    partial void OnTEN_TINHChanging(string value);
    partial void OnTEN_TINHChanged();
    partial void OnMA_MIENChanging(System.Nullable<int> value);
    partial void OnMA_MIENChanged();
    #endregion
		
		public TINH()
		{
			this._DIEM_DU_LICHes = new EntitySet<DIEM_DU_LICH>(new Action<DIEM_DU_LICH>(this.attach_DIEM_DU_LICHes), new Action<DIEM_DU_LICH>(this.detach_DIEM_DU_LICHes));
			this._MIEN = default(EntityRef<MIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_TINH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_TINH
		{
			get
			{
				return this._MA_TINH;
			}
			set
			{
				if ((this._MA_TINH != value))
				{
					this.OnMA_TINHChanging(value);
					this.SendPropertyChanging();
					this._MA_TINH = value;
					this.SendPropertyChanged("MA_TINH");
					this.OnMA_TINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TINH", DbType="NVarChar(250)")]
		public string TEN_TINH
		{
			get
			{
				return this._TEN_TINH;
			}
			set
			{
				if ((this._TEN_TINH != value))
				{
					this.OnTEN_TINHChanging(value);
					this.SendPropertyChanging();
					this._TEN_TINH = value;
					this.SendPropertyChanged("TEN_TINH");
					this.OnTEN_TINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MIEN", DbType="Int")]
		public System.Nullable<int> MA_MIEN
		{
			get
			{
				return this._MA_MIEN;
			}
			set
			{
				if ((this._MA_MIEN != value))
				{
					if (this._MIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_MIENChanging(value);
					this.SendPropertyChanging();
					this._MA_MIEN = value;
					this.SendPropertyChanged("MA_MIEN");
					this.OnMA_MIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINH_DIEM_DU_LICH", Storage="_DIEM_DU_LICHes", ThisKey="MA_TINH", OtherKey="MA_TINH")]
		public EntitySet<DIEM_DU_LICH> DIEM_DU_LICHes
		{
			get
			{
				return this._DIEM_DU_LICHes;
			}
			set
			{
				this._DIEM_DU_LICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MIEN_TINH", Storage="_MIEN", ThisKey="MA_MIEN", OtherKey="MA_MIEN", IsForeignKey=true)]
		public MIEN MIEN
		{
			get
			{
				return this._MIEN.Entity;
			}
			set
			{
				MIEN previousValue = this._MIEN.Entity;
				if (((previousValue != value) 
							|| (this._MIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MIEN.Entity = null;
						previousValue.TINHs.Remove(this);
					}
					this._MIEN.Entity = value;
					if ((value != null))
					{
						value.TINHs.Add(this);
						this._MA_MIEN = value.MA_MIEN;
					}
					else
					{
						this._MA_MIEN = default(Nullable<int>);
					}
					this.SendPropertyChanged("MIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DIEM_DU_LICHes(DIEM_DU_LICH entity)
		{
			this.SendPropertyChanging();
			entity.TINH = this;
		}
		
		private void detach_DIEM_DU_LICHes(DIEM_DU_LICH entity)
		{
			this.SendPropertyChanging();
			entity.TINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHI_TIET_TOUR")]
	public partial class CHI_TIET_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_TOUR;
		
		private int _MA_DIEM_DL;
		
		private EntityRef<CHUONG_TRINH_TOUR> _CHUONG_TRINH_TOUR;
		
		private EntityRef<DIEM_DU_LICH> _DIEM_DU_LICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_TOURChanging(int value);
    partial void OnMA_TOURChanged();
    partial void OnMA_DIEM_DLChanging(int value);
    partial void OnMA_DIEM_DLChanged();
    #endregion
		
		public CHI_TIET_TOUR()
		{
			this._CHUONG_TRINH_TOUR = default(EntityRef<CHUONG_TRINH_TOUR>);
			this._DIEM_DU_LICH = default(EntityRef<DIEM_DU_LICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_TOUR", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_TOUR
		{
			get
			{
				return this._MA_TOUR;
			}
			set
			{
				if ((this._MA_TOUR != value))
				{
					if (this._CHUONG_TRINH_TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_TOURChanging(value);
					this.SendPropertyChanging();
					this._MA_TOUR = value;
					this.SendPropertyChanged("MA_TOUR");
					this.OnMA_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DIEM_DL", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_DIEM_DL
		{
			get
			{
				return this._MA_DIEM_DL;
			}
			set
			{
				if ((this._MA_DIEM_DL != value))
				{
					if (this._DIEM_DU_LICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_DIEM_DLChanging(value);
					this.SendPropertyChanging();
					this._MA_DIEM_DL = value;
					this.SendPropertyChanged("MA_DIEM_DL");
					this.OnMA_DIEM_DLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUONG_TRINH_TOUR_CHI_TIET_TOUR", Storage="_CHUONG_TRINH_TOUR", ThisKey="MA_TOUR", OtherKey="MA_TOUR", IsForeignKey=true)]
		public CHUONG_TRINH_TOUR CHUONG_TRINH_TOUR
		{
			get
			{
				return this._CHUONG_TRINH_TOUR.Entity;
			}
			set
			{
				CHUONG_TRINH_TOUR previousValue = this._CHUONG_TRINH_TOUR.Entity;
				if (((previousValue != value) 
							|| (this._CHUONG_TRINH_TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUONG_TRINH_TOUR.Entity = null;
						previousValue.CHI_TIET_TOURs.Remove(this);
					}
					this._CHUONG_TRINH_TOUR.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_TOURs.Add(this);
						this._MA_TOUR = value.MA_TOUR;
					}
					else
					{
						this._MA_TOUR = default(int);
					}
					this.SendPropertyChanged("CHUONG_TRINH_TOUR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEM_DU_LICH_CHI_TIET_TOUR", Storage="_DIEM_DU_LICH", ThisKey="MA_DIEM_DL", OtherKey="MA_DIEM_DL", IsForeignKey=true)]
		public DIEM_DU_LICH DIEM_DU_LICH
		{
			get
			{
				return this._DIEM_DU_LICH.Entity;
			}
			set
			{
				DIEM_DU_LICH previousValue = this._DIEM_DU_LICH.Entity;
				if (((previousValue != value) 
							|| (this._DIEM_DU_LICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIEM_DU_LICH.Entity = null;
						previousValue.CHI_TIET_TOURs.Remove(this);
					}
					this._DIEM_DU_LICH.Entity = value;
					if ((value != null))
					{
						value.CHI_TIET_TOURs.Add(this);
						this._MA_DIEM_DL = value.MA_DIEM_DL;
					}
					else
					{
						this._MA_DIEM_DL = default(int);
					}
					this.SendPropertyChanged("DIEM_DU_LICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUONG_TRINH_TOUR")]
	public partial class CHUONG_TRINH_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_TOUR;
		
		private string _HINH_ANH;
		
		private string _TEN_TOUR;
		
		private System.Nullable<int> _MA_LOAI_TOUR;
		
		private System.Nullable<decimal> _GIA_NGUOI_LON;
		
		private System.Nullable<decimal> _GIA_TRE_EM;
		
		private System.Nullable<System.DateTime> _NGAY_KHOI_HANH;
		
		private System.Nullable<System.DateTime> _NGAY_KET_THUC;
		
		private System.Nullable<int> _SO_CHO;
		
		private string _GHI_CHU;
		
		private string _LICH_TRINH;
		
		private string _NOI_DUNG;
		
		private string _CHINH_SACH;
		
		private string _CAU_HOI_THUONG_GAP;
		
		private EntitySet<CHI_TIET_TOUR> _CHI_TIET_TOURs;
		
		private EntitySet<DAT_TOUR> _DAT_TOURs;
		
		private EntityRef<LOAI_TOUR> _LOAI_TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_TOURChanging(int value);
    partial void OnMA_TOURChanged();
    partial void OnHINH_ANHChanging(string value);
    partial void OnHINH_ANHChanged();
    partial void OnTEN_TOURChanging(string value);
    partial void OnTEN_TOURChanged();
    partial void OnMA_LOAI_TOURChanging(System.Nullable<int> value);
    partial void OnMA_LOAI_TOURChanged();
    partial void OnGIA_NGUOI_LONChanging(System.Nullable<decimal> value);
    partial void OnGIA_NGUOI_LONChanged();
    partial void OnGIA_TRE_EMChanging(System.Nullable<decimal> value);
    partial void OnGIA_TRE_EMChanged();
    partial void OnNGAY_KHOI_HANHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_KHOI_HANHChanged();
    partial void OnNGAY_KET_THUCChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_KET_THUCChanged();
    partial void OnSO_CHOChanging(System.Nullable<int> value);
    partial void OnSO_CHOChanged();
    partial void OnGHI_CHUChanging(string value);
    partial void OnGHI_CHUChanged();
    partial void OnLICH_TRINHChanging(string value);
    partial void OnLICH_TRINHChanged();
    partial void OnNOI_DUNGChanging(string value);
    partial void OnNOI_DUNGChanged();
    partial void OnCHINH_SACHChanging(string value);
    partial void OnCHINH_SACHChanged();
    partial void OnCAU_HOI_THUONG_GAPChanging(string value);
    partial void OnCAU_HOI_THUONG_GAPChanged();
    #endregion
		
		public CHUONG_TRINH_TOUR()
		{
			this._CHI_TIET_TOURs = new EntitySet<CHI_TIET_TOUR>(new Action<CHI_TIET_TOUR>(this.attach_CHI_TIET_TOURs), new Action<CHI_TIET_TOUR>(this.detach_CHI_TIET_TOURs));
			this._DAT_TOURs = new EntitySet<DAT_TOUR>(new Action<DAT_TOUR>(this.attach_DAT_TOURs), new Action<DAT_TOUR>(this.detach_DAT_TOURs));
			this._LOAI_TOUR = default(EntityRef<LOAI_TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_TOUR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_TOUR
		{
			get
			{
				return this._MA_TOUR;
			}
			set
			{
				if ((this._MA_TOUR != value))
				{
					this.OnMA_TOURChanging(value);
					this.SendPropertyChanging();
					this._MA_TOUR = value;
					this.SendPropertyChanged("MA_TOUR");
					this.OnMA_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_ANH", DbType="NChar(250)")]
		public string HINH_ANH
		{
			get
			{
				return this._HINH_ANH;
			}
			set
			{
				if ((this._HINH_ANH != value))
				{
					this.OnHINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._HINH_ANH = value;
					this.SendPropertyChanged("HINH_ANH");
					this.OnHINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TOUR", DbType="NVarChar(250)")]
		public string TEN_TOUR
		{
			get
			{
				return this._TEN_TOUR;
			}
			set
			{
				if ((this._TEN_TOUR != value))
				{
					this.OnTEN_TOURChanging(value);
					this.SendPropertyChanging();
					this._TEN_TOUR = value;
					this.SendPropertyChanged("TEN_TOUR");
					this.OnTEN_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LOAI_TOUR", DbType="Int")]
		public System.Nullable<int> MA_LOAI_TOUR
		{
			get
			{
				return this._MA_LOAI_TOUR;
			}
			set
			{
				if ((this._MA_LOAI_TOUR != value))
				{
					if (this._LOAI_TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LOAI_TOURChanging(value);
					this.SendPropertyChanging();
					this._MA_LOAI_TOUR = value;
					this.SendPropertyChanged("MA_LOAI_TOUR");
					this.OnMA_LOAI_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_NGUOI_LON", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIA_NGUOI_LON
		{
			get
			{
				return this._GIA_NGUOI_LON;
			}
			set
			{
				if ((this._GIA_NGUOI_LON != value))
				{
					this.OnGIA_NGUOI_LONChanging(value);
					this.SendPropertyChanging();
					this._GIA_NGUOI_LON = value;
					this.SendPropertyChanged("GIA_NGUOI_LON");
					this.OnGIA_NGUOI_LONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_TRE_EM", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIA_TRE_EM
		{
			get
			{
				return this._GIA_TRE_EM;
			}
			set
			{
				if ((this._GIA_TRE_EM != value))
				{
					this.OnGIA_TRE_EMChanging(value);
					this.SendPropertyChanging();
					this._GIA_TRE_EM = value;
					this.SendPropertyChanged("GIA_TRE_EM");
					this.OnGIA_TRE_EMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_KHOI_HANH", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_KHOI_HANH
		{
			get
			{
				return this._NGAY_KHOI_HANH;
			}
			set
			{
				if ((this._NGAY_KHOI_HANH != value))
				{
					this.OnNGAY_KHOI_HANHChanging(value);
					this.SendPropertyChanging();
					this._NGAY_KHOI_HANH = value;
					this.SendPropertyChanged("NGAY_KHOI_HANH");
					this.OnNGAY_KHOI_HANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_KET_THUC", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_KET_THUC
		{
			get
			{
				return this._NGAY_KET_THUC;
			}
			set
			{
				if ((this._NGAY_KET_THUC != value))
				{
					this.OnNGAY_KET_THUCChanging(value);
					this.SendPropertyChanging();
					this._NGAY_KET_THUC = value;
					this.SendPropertyChanged("NGAY_KET_THUC");
					this.OnNGAY_KET_THUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_CHO", DbType="Int")]
		public System.Nullable<int> SO_CHO
		{
			get
			{
				return this._SO_CHO;
			}
			set
			{
				if ((this._SO_CHO != value))
				{
					this.OnSO_CHOChanging(value);
					this.SendPropertyChanging();
					this._SO_CHO = value;
					this.SendPropertyChanged("SO_CHO");
					this.OnSO_CHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(MAX)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this.OnGHI_CHUChanging(value);
					this.SendPropertyChanging();
					this._GHI_CHU = value;
					this.SendPropertyChanged("GHI_CHU");
					this.OnGHI_CHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LICH_TRINH", DbType="NVarChar(MAX)")]
		public string LICH_TRINH
		{
			get
			{
				return this._LICH_TRINH;
			}
			set
			{
				if ((this._LICH_TRINH != value))
				{
					this.OnLICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._LICH_TRINH = value;
					this.SendPropertyChanged("LICH_TRINH");
					this.OnLICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOI_DUNG", DbType="NVarChar(MAX)")]
		public string NOI_DUNG
		{
			get
			{
				return this._NOI_DUNG;
			}
			set
			{
				if ((this._NOI_DUNG != value))
				{
					this.OnNOI_DUNGChanging(value);
					this.SendPropertyChanging();
					this._NOI_DUNG = value;
					this.SendPropertyChanged("NOI_DUNG");
					this.OnNOI_DUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHINH_SACH", DbType="NVarChar(MAX)")]
		public string CHINH_SACH
		{
			get
			{
				return this._CHINH_SACH;
			}
			set
			{
				if ((this._CHINH_SACH != value))
				{
					this.OnCHINH_SACHChanging(value);
					this.SendPropertyChanging();
					this._CHINH_SACH = value;
					this.SendPropertyChanged("CHINH_SACH");
					this.OnCHINH_SACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAU_HOI_THUONG_GAP", DbType="NVarChar(MAX)")]
		public string CAU_HOI_THUONG_GAP
		{
			get
			{
				return this._CAU_HOI_THUONG_GAP;
			}
			set
			{
				if ((this._CAU_HOI_THUONG_GAP != value))
				{
					this.OnCAU_HOI_THUONG_GAPChanging(value);
					this.SendPropertyChanging();
					this._CAU_HOI_THUONG_GAP = value;
					this.SendPropertyChanged("CAU_HOI_THUONG_GAP");
					this.OnCAU_HOI_THUONG_GAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUONG_TRINH_TOUR_CHI_TIET_TOUR", Storage="_CHI_TIET_TOURs", ThisKey="MA_TOUR", OtherKey="MA_TOUR")]
		public EntitySet<CHI_TIET_TOUR> CHI_TIET_TOURs
		{
			get
			{
				return this._CHI_TIET_TOURs;
			}
			set
			{
				this._CHI_TIET_TOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUONG_TRINH_TOUR_DAT_TOUR", Storage="_DAT_TOURs", ThisKey="MA_TOUR", OtherKey="MA_TOUR")]
		public EntitySet<DAT_TOUR> DAT_TOURs
		{
			get
			{
				return this._DAT_TOURs;
			}
			set
			{
				this._DAT_TOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_TOUR_CHUONG_TRINH_TOUR", Storage="_LOAI_TOUR", ThisKey="MA_LOAI_TOUR", OtherKey="MA_LOAI_TOUR", IsForeignKey=true)]
		public LOAI_TOUR LOAI_TOUR
		{
			get
			{
				return this._LOAI_TOUR.Entity;
			}
			set
			{
				LOAI_TOUR previousValue = this._LOAI_TOUR.Entity;
				if (((previousValue != value) 
							|| (this._LOAI_TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI_TOUR.Entity = null;
						previousValue.CHUONG_TRINH_TOURs.Remove(this);
					}
					this._LOAI_TOUR.Entity = value;
					if ((value != null))
					{
						value.CHUONG_TRINH_TOURs.Add(this);
						this._MA_LOAI_TOUR = value.MA_LOAI_TOUR;
					}
					else
					{
						this._MA_LOAI_TOUR = default(Nullable<int>);
					}
					this.SendPropertyChanged("LOAI_TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHI_TIET_TOURs(CHI_TIET_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.CHUONG_TRINH_TOUR = this;
		}
		
		private void detach_CHI_TIET_TOURs(CHI_TIET_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.CHUONG_TRINH_TOUR = null;
		}
		
		private void attach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.CHUONG_TRINH_TOUR = this;
		}
		
		private void detach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.CHUONG_TRINH_TOUR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DAT_TOUR")]
	public partial class DAT_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_DAT_TOUR;
		
		private int _MA_TOUR;
		
		private int _MA_KH;
		
		private System.Nullable<decimal> _GIA_NGUOI_LON;
		
		private System.Nullable<decimal> _GIA_TRE_EM;
		
		private System.Nullable<int> _SO_NGAY;
		
		private System.Nullable<int> _SO_CHO_NGUOI_LON;
		
		private System.Nullable<int> _SO_CHO_TRE_EM;
		
		private System.Nullable<System.DateTime> _NGAY_DAT;
		
		private System.Nullable<decimal> _PHU_THU;
		
		private System.Nullable<decimal> _THANH_TIEN;
		
		private EntityRef<CHUONG_TRINH_TOUR> _CHUONG_TRINH_TOUR;
		
		private EntityRef<KHACH_HANG> _KHACH_HANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DAT_TOURChanging(int value);
    partial void OnMA_DAT_TOURChanged();
    partial void OnMA_TOURChanging(int value);
    partial void OnMA_TOURChanged();
    partial void OnMA_KHChanging(int value);
    partial void OnMA_KHChanged();
    partial void OnGIA_NGUOI_LONChanging(System.Nullable<decimal> value);
    partial void OnGIA_NGUOI_LONChanged();
    partial void OnGIA_TRE_EMChanging(System.Nullable<decimal> value);
    partial void OnGIA_TRE_EMChanged();
    partial void OnSO_NGAYChanging(System.Nullable<int> value);
    partial void OnSO_NGAYChanged();
    partial void OnSO_CHO_NGUOI_LONChanging(System.Nullable<int> value);
    partial void OnSO_CHO_NGUOI_LONChanged();
    partial void OnSO_CHO_TRE_EMChanging(System.Nullable<int> value);
    partial void OnSO_CHO_TRE_EMChanged();
    partial void OnNGAY_DATChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_DATChanged();
    partial void OnPHU_THUChanging(System.Nullable<decimal> value);
    partial void OnPHU_THUChanged();
    partial void OnTHANH_TIENChanging(System.Nullable<decimal> value);
    partial void OnTHANH_TIENChanged();
    #endregion
		
		public DAT_TOUR()
		{
			this._CHUONG_TRINH_TOUR = default(EntityRef<CHUONG_TRINH_TOUR>);
			this._KHACH_HANG = default(EntityRef<KHACH_HANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DAT_TOUR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_DAT_TOUR
		{
			get
			{
				return this._MA_DAT_TOUR;
			}
			set
			{
				if ((this._MA_DAT_TOUR != value))
				{
					this.OnMA_DAT_TOURChanging(value);
					this.SendPropertyChanging();
					this._MA_DAT_TOUR = value;
					this.SendPropertyChanged("MA_DAT_TOUR");
					this.OnMA_DAT_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_TOUR", DbType="Int NOT NULL")]
		public int MA_TOUR
		{
			get
			{
				return this._MA_TOUR;
			}
			set
			{
				if ((this._MA_TOUR != value))
				{
					if ((this._CHUONG_TRINH_TOUR.HasLoadedOrAssignedValue || this._KHACH_HANG.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_TOURChanging(value);
					this.SendPropertyChanging();
					this._MA_TOUR = value;
					this.SendPropertyChanged("MA_TOUR");
					this.OnMA_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", DbType="Int NOT NULL")]
		public int MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_NGUOI_LON", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIA_NGUOI_LON
		{
			get
			{
				return this._GIA_NGUOI_LON;
			}
			set
			{
				if ((this._GIA_NGUOI_LON != value))
				{
					this.OnGIA_NGUOI_LONChanging(value);
					this.SendPropertyChanging();
					this._GIA_NGUOI_LON = value;
					this.SendPropertyChanged("GIA_NGUOI_LON");
					this.OnGIA_NGUOI_LONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_TRE_EM", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> GIA_TRE_EM
		{
			get
			{
				return this._GIA_TRE_EM;
			}
			set
			{
				if ((this._GIA_TRE_EM != value))
				{
					this.OnGIA_TRE_EMChanging(value);
					this.SendPropertyChanging();
					this._GIA_TRE_EM = value;
					this.SendPropertyChanged("GIA_TRE_EM");
					this.OnGIA_TRE_EMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_NGAY", DbType="Int")]
		public System.Nullable<int> SO_NGAY
		{
			get
			{
				return this._SO_NGAY;
			}
			set
			{
				if ((this._SO_NGAY != value))
				{
					this.OnSO_NGAYChanging(value);
					this.SendPropertyChanging();
					this._SO_NGAY = value;
					this.SendPropertyChanged("SO_NGAY");
					this.OnSO_NGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_CHO_NGUOI_LON", DbType="Int")]
		public System.Nullable<int> SO_CHO_NGUOI_LON
		{
			get
			{
				return this._SO_CHO_NGUOI_LON;
			}
			set
			{
				if ((this._SO_CHO_NGUOI_LON != value))
				{
					this.OnSO_CHO_NGUOI_LONChanging(value);
					this.SendPropertyChanging();
					this._SO_CHO_NGUOI_LON = value;
					this.SendPropertyChanged("SO_CHO_NGUOI_LON");
					this.OnSO_CHO_NGUOI_LONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_CHO_TRE_EM", DbType="Int")]
		public System.Nullable<int> SO_CHO_TRE_EM
		{
			get
			{
				return this._SO_CHO_TRE_EM;
			}
			set
			{
				if ((this._SO_CHO_TRE_EM != value))
				{
					this.OnSO_CHO_TRE_EMChanging(value);
					this.SendPropertyChanging();
					this._SO_CHO_TRE_EM = value;
					this.SendPropertyChanged("SO_CHO_TRE_EM");
					this.OnSO_CHO_TRE_EMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_DAT
		{
			get
			{
				return this._NGAY_DAT;
			}
			set
			{
				if ((this._NGAY_DAT != value))
				{
					this.OnNGAY_DATChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DAT = value;
					this.SendPropertyChanged("NGAY_DAT");
					this.OnNGAY_DATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHU_THU", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PHU_THU
		{
			get
			{
				return this._PHU_THU;
			}
			set
			{
				if ((this._PHU_THU != value))
				{
					this.OnPHU_THUChanging(value);
					this.SendPropertyChanging();
					this._PHU_THU = value;
					this.SendPropertyChanged("PHU_THU");
					this.OnPHU_THUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANH_TIEN", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> THANH_TIEN
		{
			get
			{
				return this._THANH_TIEN;
			}
			set
			{
				if ((this._THANH_TIEN != value))
				{
					this.OnTHANH_TIENChanging(value);
					this.SendPropertyChanging();
					this._THANH_TIEN = value;
					this.SendPropertyChanged("THANH_TIEN");
					this.OnTHANH_TIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUONG_TRINH_TOUR_DAT_TOUR", Storage="_CHUONG_TRINH_TOUR", ThisKey="MA_TOUR", OtherKey="MA_TOUR", IsForeignKey=true)]
		public CHUONG_TRINH_TOUR CHUONG_TRINH_TOUR
		{
			get
			{
				return this._CHUONG_TRINH_TOUR.Entity;
			}
			set
			{
				CHUONG_TRINH_TOUR previousValue = this._CHUONG_TRINH_TOUR.Entity;
				if (((previousValue != value) 
							|| (this._CHUONG_TRINH_TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUONG_TRINH_TOUR.Entity = null;
						previousValue.DAT_TOURs.Remove(this);
					}
					this._CHUONG_TRINH_TOUR.Entity = value;
					if ((value != null))
					{
						value.DAT_TOURs.Add(this);
						this._MA_TOUR = value.MA_TOUR;
					}
					else
					{
						this._MA_TOUR = default(int);
					}
					this.SendPropertyChanged("CHUONG_TRINH_TOUR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DAT_TOUR", Storage="_KHACH_HANG", ThisKey="MA_TOUR", OtherKey="MA_KH", IsForeignKey=true)]
		public KHACH_HANG KHACH_HANG
		{
			get
			{
				return this._KHACH_HANG.Entity;
			}
			set
			{
				KHACH_HANG previousValue = this._KHACH_HANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACH_HANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACH_HANG.Entity = null;
						previousValue.DAT_TOURs.Remove(this);
					}
					this._KHACH_HANG.Entity = value;
					if ((value != null))
					{
						value.DAT_TOURs.Add(this);
						this._MA_TOUR = value.MA_KH;
					}
					else
					{
						this._MA_TOUR = default(int);
					}
					this.SendPropertyChanged("KHACH_HANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DIEM_DU_LICH")]
	public partial class DIEM_DU_LICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_DIEM_DL;
		
		private string _HINH_ANH;
		
		private string _TEN_DIEM_DL;
		
		private string _THONG_TIN;
		
		private int _MA_TINH;
		
		private EntitySet<CHI_TIET_TOUR> _CHI_TIET_TOURs;
		
		private EntitySet<HINH_ANH> _HINH_ANHs;
		
		private EntityRef<TINH> _TINH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_DIEM_DLChanging(int value);
    partial void OnMA_DIEM_DLChanged();
    partial void OnHINH_ANHChanging(string value);
    partial void OnHINH_ANHChanged();
    partial void OnTEN_DIEM_DLChanging(string value);
    partial void OnTEN_DIEM_DLChanged();
    partial void OnTHONG_TINChanging(string value);
    partial void OnTHONG_TINChanged();
    partial void OnMA_TINHChanging(int value);
    partial void OnMA_TINHChanged();
    #endregion
		
		public DIEM_DU_LICH()
		{
			this._CHI_TIET_TOURs = new EntitySet<CHI_TIET_TOUR>(new Action<CHI_TIET_TOUR>(this.attach_CHI_TIET_TOURs), new Action<CHI_TIET_TOUR>(this.detach_CHI_TIET_TOURs));
			this._HINH_ANHs = new EntitySet<HINH_ANH>(new Action<HINH_ANH>(this.attach_HINH_ANHs), new Action<HINH_ANH>(this.detach_HINH_ANHs));
			this._TINH = default(EntityRef<TINH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DIEM_DL", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_DIEM_DL
		{
			get
			{
				return this._MA_DIEM_DL;
			}
			set
			{
				if ((this._MA_DIEM_DL != value))
				{
					this.OnMA_DIEM_DLChanging(value);
					this.SendPropertyChanging();
					this._MA_DIEM_DL = value;
					this.SendPropertyChanged("MA_DIEM_DL");
					this.OnMA_DIEM_DLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_ANH", DbType="NChar(250)")]
		public string HINH_ANH
		{
			get
			{
				return this._HINH_ANH;
			}
			set
			{
				if ((this._HINH_ANH != value))
				{
					this.OnHINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._HINH_ANH = value;
					this.SendPropertyChanged("HINH_ANH");
					this.OnHINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_DIEM_DL", DbType="NVarChar(250)")]
		public string TEN_DIEM_DL
		{
			get
			{
				return this._TEN_DIEM_DL;
			}
			set
			{
				if ((this._TEN_DIEM_DL != value))
				{
					this.OnTEN_DIEM_DLChanging(value);
					this.SendPropertyChanging();
					this._TEN_DIEM_DL = value;
					this.SendPropertyChanged("TEN_DIEM_DL");
					this.OnTEN_DIEM_DLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THONG_TIN", DbType="NVarChar(250)")]
		public string THONG_TIN
		{
			get
			{
				return this._THONG_TIN;
			}
			set
			{
				if ((this._THONG_TIN != value))
				{
					this.OnTHONG_TINChanging(value);
					this.SendPropertyChanging();
					this._THONG_TIN = value;
					this.SendPropertyChanged("THONG_TIN");
					this.OnTHONG_TINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_TINH", DbType="Int NOT NULL")]
		public int MA_TINH
		{
			get
			{
				return this._MA_TINH;
			}
			set
			{
				if ((this._MA_TINH != value))
				{
					if (this._TINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_TINHChanging(value);
					this.SendPropertyChanging();
					this._MA_TINH = value;
					this.SendPropertyChanged("MA_TINH");
					this.OnMA_TINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEM_DU_LICH_CHI_TIET_TOUR", Storage="_CHI_TIET_TOURs", ThisKey="MA_DIEM_DL", OtherKey="MA_DIEM_DL")]
		public EntitySet<CHI_TIET_TOUR> CHI_TIET_TOURs
		{
			get
			{
				return this._CHI_TIET_TOURs;
			}
			set
			{
				this._CHI_TIET_TOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEM_DU_LICH_HINH_ANH", Storage="_HINH_ANHs", ThisKey="MA_DIEM_DL", OtherKey="MA_DIEM_DL")]
		public EntitySet<HINH_ANH> HINH_ANHs
		{
			get
			{
				return this._HINH_ANHs;
			}
			set
			{
				this._HINH_ANHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TINH_DIEM_DU_LICH", Storage="_TINH", ThisKey="MA_TINH", OtherKey="MA_TINH", IsForeignKey=true)]
		public TINH TINH
		{
			get
			{
				return this._TINH.Entity;
			}
			set
			{
				TINH previousValue = this._TINH.Entity;
				if (((previousValue != value) 
							|| (this._TINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TINH.Entity = null;
						previousValue.DIEM_DU_LICHes.Remove(this);
					}
					this._TINH.Entity = value;
					if ((value != null))
					{
						value.DIEM_DU_LICHes.Add(this);
						this._MA_TINH = value.MA_TINH;
					}
					else
					{
						this._MA_TINH = default(int);
					}
					this.SendPropertyChanged("TINH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHI_TIET_TOURs(CHI_TIET_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.DIEM_DU_LICH = this;
		}
		
		private void detach_CHI_TIET_TOURs(CHI_TIET_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.DIEM_DU_LICH = null;
		}
		
		private void attach_HINH_ANHs(HINH_ANH entity)
		{
			this.SendPropertyChanging();
			entity.DIEM_DU_LICH = this;
		}
		
		private void detach_HINH_ANHs(HINH_ANH entity)
		{
			this.SendPropertyChanging();
			entity.DIEM_DU_LICH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HINH_ANH")]
	public partial class HINH_ANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_HINH_ANH;
		
		private string _TEN_HINH_ANH;
		
		private string _LINK_HINH_ANH;
		
		private int _MA_DIEM_DL;
		
		private EntityRef<DIEM_DU_LICH> _DIEM_DU_LICH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HINH_ANHChanging(int value);
    partial void OnMA_HINH_ANHChanged();
    partial void OnTEN_HINH_ANHChanging(string value);
    partial void OnTEN_HINH_ANHChanged();
    partial void OnLINK_HINH_ANHChanging(string value);
    partial void OnLINK_HINH_ANHChanged();
    partial void OnMA_DIEM_DLChanging(int value);
    partial void OnMA_DIEM_DLChanged();
    #endregion
		
		public HINH_ANH()
		{
			this._DIEM_DU_LICH = default(EntityRef<DIEM_DU_LICH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HINH_ANH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_HINH_ANH
		{
			get
			{
				return this._MA_HINH_ANH;
			}
			set
			{
				if ((this._MA_HINH_ANH != value))
				{
					this.OnMA_HINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._MA_HINH_ANH = value;
					this.SendPropertyChanged("MA_HINH_ANH");
					this.OnMA_HINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_HINH_ANH", DbType="NVarChar(250)")]
		public string TEN_HINH_ANH
		{
			get
			{
				return this._TEN_HINH_ANH;
			}
			set
			{
				if ((this._TEN_HINH_ANH != value))
				{
					this.OnTEN_HINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._TEN_HINH_ANH = value;
					this.SendPropertyChanged("TEN_HINH_ANH");
					this.OnTEN_HINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LINK_HINH_ANH", DbType="NChar(250)")]
		public string LINK_HINH_ANH
		{
			get
			{
				return this._LINK_HINH_ANH;
			}
			set
			{
				if ((this._LINK_HINH_ANH != value))
				{
					this.OnLINK_HINH_ANHChanging(value);
					this.SendPropertyChanging();
					this._LINK_HINH_ANH = value;
					this.SendPropertyChanged("LINK_HINH_ANH");
					this.OnLINK_HINH_ANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_DIEM_DL", DbType="Int NOT NULL")]
		public int MA_DIEM_DL
		{
			get
			{
				return this._MA_DIEM_DL;
			}
			set
			{
				if ((this._MA_DIEM_DL != value))
				{
					if (this._DIEM_DU_LICH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_DIEM_DLChanging(value);
					this.SendPropertyChanging();
					this._MA_DIEM_DL = value;
					this.SendPropertyChanged("MA_DIEM_DL");
					this.OnMA_DIEM_DLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DIEM_DU_LICH_HINH_ANH", Storage="_DIEM_DU_LICH", ThisKey="MA_DIEM_DL", OtherKey="MA_DIEM_DL", IsForeignKey=true)]
		public DIEM_DU_LICH DIEM_DU_LICH
		{
			get
			{
				return this._DIEM_DU_LICH.Entity;
			}
			set
			{
				DIEM_DU_LICH previousValue = this._DIEM_DU_LICH.Entity;
				if (((previousValue != value) 
							|| (this._DIEM_DU_LICH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DIEM_DU_LICH.Entity = null;
						previousValue.HINH_ANHs.Remove(this);
					}
					this._DIEM_DU_LICH.Entity = value;
					if ((value != null))
					{
						value.HINH_ANHs.Add(this);
						this._MA_DIEM_DL = value.MA_DIEM_DL;
					}
					else
					{
						this._MA_DIEM_DL = default(int);
					}
					this.SendPropertyChanged("DIEM_DU_LICH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACH_HANG")]
	public partial class KHACH_HANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_KH;
		
		private string _TEN_KH;
		
		private System.Nullable<System.DateTime> _NGAY_SINH;
		
		private string _GIOI_TINH;
		
		private string _CMND;
		
		private string _PASSPORT;
		
		private string _MA_QUOC_GIA;
		
		private string _DIA_CHI;
		
		private string _EMAIL;
		
		private string _TAI_KHOAN_KH;
		
		private string _MAT_KHAU_KH;
		
		private string _DIEN_THOAI;
		
		private string _GHI_CHU;
		
		private EntitySet<DAT_TOUR> _DAT_TOURs;
		
		private EntityRef<QUOC_GIA> _QUOC_GIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_KHChanging(int value);
    partial void OnMA_KHChanged();
    partial void OnTEN_KHChanging(string value);
    partial void OnTEN_KHChanged();
    partial void OnNGAY_SINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_SINHChanged();
    partial void OnGIOI_TINHChanging(string value);
    partial void OnGIOI_TINHChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnPASSPORTChanging(string value);
    partial void OnPASSPORTChanged();
    partial void OnMA_QUOC_GIAChanging(string value);
    partial void OnMA_QUOC_GIAChanged();
    partial void OnDIA_CHIChanging(string value);
    partial void OnDIA_CHIChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnTAI_KHOAN_KHChanging(string value);
    partial void OnTAI_KHOAN_KHChanged();
    partial void OnMAT_KHAU_KHChanging(string value);
    partial void OnMAT_KHAU_KHChanged();
    partial void OnDIEN_THOAIChanging(string value);
    partial void OnDIEN_THOAIChanged();
    partial void OnGHI_CHUChanging(string value);
    partial void OnGHI_CHUChanged();
    #endregion
		
		public KHACH_HANG()
		{
			this._DAT_TOURs = new EntitySet<DAT_TOUR>(new Action<DAT_TOUR>(this.attach_DAT_TOURs), new Action<DAT_TOUR>(this.detach_DAT_TOURs));
			this._QUOC_GIA = default(EntityRef<QUOC_GIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_KH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_KH
		{
			get
			{
				return this._MA_KH;
			}
			set
			{
				if ((this._MA_KH != value))
				{
					this.OnMA_KHChanging(value);
					this.SendPropertyChanging();
					this._MA_KH = value;
					this.SendPropertyChanged("MA_KH");
					this.OnMA_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_KH", DbType="NVarChar(250)")]
		public string TEN_KH
		{
			get
			{
				return this._TEN_KH;
			}
			set
			{
				if ((this._TEN_KH != value))
				{
					this.OnTEN_KHChanging(value);
					this.SendPropertyChanging();
					this._TEN_KH = value;
					this.SendPropertyChanged("TEN_KH");
					this.OnTEN_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_SINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAY_SINH
		{
			get
			{
				return this._NGAY_SINH;
			}
			set
			{
				if ((this._NGAY_SINH != value))
				{
					this.OnNGAY_SINHChanging(value);
					this.SendPropertyChanging();
					this._NGAY_SINH = value;
					this.SendPropertyChanged("NGAY_SINH");
					this.OnNGAY_SINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOI_TINH", DbType="NVarChar(10)")]
		public string GIOI_TINH
		{
			get
			{
				return this._GIOI_TINH;
			}
			set
			{
				if ((this._GIOI_TINH != value))
				{
					this.OnGIOI_TINHChanging(value);
					this.SendPropertyChanging();
					this._GIOI_TINH = value;
					this.SendPropertyChanged("GIOI_TINH");
					this.OnGIOI_TINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="NChar(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSPORT", DbType="NChar(20)")]
		public string PASSPORT
		{
			get
			{
				return this._PASSPORT;
			}
			set
			{
				if ((this._PASSPORT != value))
				{
					this.OnPASSPORTChanging(value);
					this.SendPropertyChanging();
					this._PASSPORT = value;
					this.SendPropertyChanged("PASSPORT");
					this.OnPASSPORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_QUOC_GIA", DbType="NChar(10)")]
		public string MA_QUOC_GIA
		{
			get
			{
				return this._MA_QUOC_GIA;
			}
			set
			{
				if ((this._MA_QUOC_GIA != value))
				{
					if (this._QUOC_GIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_QUOC_GIAChanging(value);
					this.SendPropertyChanging();
					this._MA_QUOC_GIA = value;
					this.SendPropertyChanged("MA_QUOC_GIA");
					this.OnMA_QUOC_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI", DbType="NVarChar(250)")]
		public string DIA_CHI
		{
			get
			{
				return this._DIA_CHI;
			}
			set
			{
				if ((this._DIA_CHI != value))
				{
					this.OnDIA_CHIChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI = value;
					this.SendPropertyChanged("DIA_CHI");
					this.OnDIA_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NChar(250)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAI_KHOAN_KH", DbType="NChar(250)")]
		public string TAI_KHOAN_KH
		{
			get
			{
				return this._TAI_KHOAN_KH;
			}
			set
			{
				if ((this._TAI_KHOAN_KH != value))
				{
					this.OnTAI_KHOAN_KHChanging(value);
					this.SendPropertyChanging();
					this._TAI_KHOAN_KH = value;
					this.SendPropertyChanged("TAI_KHOAN_KH");
					this.OnTAI_KHOAN_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT_KHAU_KH", DbType="NChar(20)")]
		public string MAT_KHAU_KH
		{
			get
			{
				return this._MAT_KHAU_KH;
			}
			set
			{
				if ((this._MAT_KHAU_KH != value))
				{
					this.OnMAT_KHAU_KHChanging(value);
					this.SendPropertyChanging();
					this._MAT_KHAU_KH = value;
					this.SendPropertyChanged("MAT_KHAU_KH");
					this.OnMAT_KHAU_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEN_THOAI", DbType="NChar(20)")]
		public string DIEN_THOAI
		{
			get
			{
				return this._DIEN_THOAI;
			}
			set
			{
				if ((this._DIEN_THOAI != value))
				{
					this.OnDIEN_THOAIChanging(value);
					this.SendPropertyChanging();
					this._DIEN_THOAI = value;
					this.SendPropertyChanged("DIEN_THOAI");
					this.OnDIEN_THOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(250)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this.OnGHI_CHUChanging(value);
					this.SendPropertyChanging();
					this._GHI_CHU = value;
					this.SendPropertyChanged("GHI_CHU");
					this.OnGHI_CHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACH_HANG_DAT_TOUR", Storage="_DAT_TOURs", ThisKey="MA_KH", OtherKey="MA_TOUR")]
		public EntitySet<DAT_TOUR> DAT_TOURs
		{
			get
			{
				return this._DAT_TOURs;
			}
			set
			{
				this._DAT_TOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUOC_GIA_KHACH_HANG", Storage="_QUOC_GIA", ThisKey="MA_QUOC_GIA", OtherKey="MA_QUOC_GIA", IsForeignKey=true)]
		public QUOC_GIA QUOC_GIA
		{
			get
			{
				return this._QUOC_GIA.Entity;
			}
			set
			{
				QUOC_GIA previousValue = this._QUOC_GIA.Entity;
				if (((previousValue != value) 
							|| (this._QUOC_GIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QUOC_GIA.Entity = null;
						previousValue.KHACH_HANGs.Remove(this);
					}
					this._QUOC_GIA.Entity = value;
					if ((value != null))
					{
						value.KHACH_HANGs.Add(this);
						this._MA_QUOC_GIA = value.MA_QUOC_GIA;
					}
					else
					{
						this._MA_QUOC_GIA = default(string);
					}
					this.SendPropertyChanged("QUOC_GIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = this;
		}
		
		private void detach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.KHACH_HANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_TOUR")]
	public partial class LOAI_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_LOAI_TOUR;
		
		private string _TEN_LOAI;
		
		private EntitySet<CHUONG_TRINH_TOUR> _CHUONG_TRINH_TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_LOAI_TOURChanging(int value);
    partial void OnMA_LOAI_TOURChanged();
    partial void OnTEN_LOAIChanging(string value);
    partial void OnTEN_LOAIChanged();
    #endregion
		
		public LOAI_TOUR()
		{
			this._CHUONG_TRINH_TOURs = new EntitySet<CHUONG_TRINH_TOUR>(new Action<CHUONG_TRINH_TOUR>(this.attach_CHUONG_TRINH_TOURs), new Action<CHUONG_TRINH_TOUR>(this.detach_CHUONG_TRINH_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LOAI_TOUR", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MA_LOAI_TOUR
		{
			get
			{
				return this._MA_LOAI_TOUR;
			}
			set
			{
				if ((this._MA_LOAI_TOUR != value))
				{
					this.OnMA_LOAI_TOURChanging(value);
					this.SendPropertyChanging();
					this._MA_LOAI_TOUR = value;
					this.SendPropertyChanged("MA_LOAI_TOUR");
					this.OnMA_LOAI_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TEN_LOAI
		{
			get
			{
				return this._TEN_LOAI;
			}
			set
			{
				if ((this._TEN_LOAI != value))
				{
					this.OnTEN_LOAIChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAI = value;
					this.SendPropertyChanged("TEN_LOAI");
					this.OnTEN_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_TOUR_CHUONG_TRINH_TOUR", Storage="_CHUONG_TRINH_TOURs", ThisKey="MA_LOAI_TOUR", OtherKey="MA_LOAI_TOUR")]
		public EntitySet<CHUONG_TRINH_TOUR> CHUONG_TRINH_TOURs
		{
			get
			{
				return this._CHUONG_TRINH_TOURs;
			}
			set
			{
				this._CHUONG_TRINH_TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHUONG_TRINH_TOURs(CHUONG_TRINH_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_TOUR = this;
		}
		
		private void detach_CHUONG_TRINH_TOURs(CHUONG_TRINH_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_TOUR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MIEN")]
	public partial class MIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_MIEN;
		
		private string _TEN_MIEN;
		
		private System.Nullable<bool> _TRONG_NGOAI_NUOC;
		
		private EntitySet<TINH> _TINHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_MIENChanging(int value);
    partial void OnMA_MIENChanged();
    partial void OnTEN_MIENChanging(string value);
    partial void OnTEN_MIENChanged();
    partial void OnTRONG_NGOAI_NUOCChanging(System.Nullable<bool> value);
    partial void OnTRONG_NGOAI_NUOCChanged();
    #endregion
		
		public MIEN()
		{
			this._TINHs = new EntitySet<TINH>(new Action<TINH>(this.attach_TINHs), new Action<TINH>(this.detach_TINHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MIEN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_MIEN
		{
			get
			{
				return this._MA_MIEN;
			}
			set
			{
				if ((this._MA_MIEN != value))
				{
					this.OnMA_MIENChanging(value);
					this.SendPropertyChanging();
					this._MA_MIEN = value;
					this.SendPropertyChanged("MA_MIEN");
					this.OnMA_MIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_MIEN", DbType="NVarChar(250)")]
		public string TEN_MIEN
		{
			get
			{
				return this._TEN_MIEN;
			}
			set
			{
				if ((this._TEN_MIEN != value))
				{
					this.OnTEN_MIENChanging(value);
					this.SendPropertyChanging();
					this._TEN_MIEN = value;
					this.SendPropertyChanged("TEN_MIEN");
					this.OnTEN_MIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRONG_NGOAI_NUOC", DbType="Bit")]
		public System.Nullable<bool> TRONG_NGOAI_NUOC
		{
			get
			{
				return this._TRONG_NGOAI_NUOC;
			}
			set
			{
				if ((this._TRONG_NGOAI_NUOC != value))
				{
					this.OnTRONG_NGOAI_NUOCChanging(value);
					this.SendPropertyChanging();
					this._TRONG_NGOAI_NUOC = value;
					this.SendPropertyChanged("TRONG_NGOAI_NUOC");
					this.OnTRONG_NGOAI_NUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MIEN_TINH", Storage="_TINHs", ThisKey="MA_MIEN", OtherKey="MA_MIEN")]
		public EntitySet<TINH> TINHs
		{
			get
			{
				return this._TINHs;
			}
			set
			{
				this._TINHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TINHs(TINH entity)
		{
			this.SendPropertyChanging();
			entity.MIEN = this;
		}
		
		private void detach_TINHs(TINH entity)
		{
			this.SendPropertyChanging();
			entity.MIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUAN_TRI_VIEN")]
	public partial class QUAN_TRI_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TAI_KHOAN;
		
		private string _MAT_KHAU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTAI_KHOANChanging(string value);
    partial void OnTAI_KHOANChanged();
    partial void OnMAT_KHAUChanging(string value);
    partial void OnMAT_KHAUChanged();
    #endregion
		
		public QUAN_TRI_VIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAI_KHOAN", DbType="NChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TAI_KHOAN
		{
			get
			{
				return this._TAI_KHOAN;
			}
			set
			{
				if ((this._TAI_KHOAN != value))
				{
					this.OnTAI_KHOANChanging(value);
					this.SendPropertyChanging();
					this._TAI_KHOAN = value;
					this.SendPropertyChanged("TAI_KHOAN");
					this.OnTAI_KHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT_KHAU", DbType="NChar(20)")]
		public string MAT_KHAU
		{
			get
			{
				return this._MAT_KHAU;
			}
			set
			{
				if ((this._MAT_KHAU != value))
				{
					this.OnMAT_KHAUChanging(value);
					this.SendPropertyChanging();
					this._MAT_KHAU = value;
					this.SendPropertyChanged("MAT_KHAU");
					this.OnMAT_KHAUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUOC_GIA")]
	public partial class QUOC_GIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_QUOC_GIA;
		
		private string _TEN_QUOC_GIA;
		
		private string _GHI_CHU;
		
		private EntitySet<KHACH_HANG> _KHACH_HANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_QUOC_GIAChanging(string value);
    partial void OnMA_QUOC_GIAChanged();
    partial void OnTEN_QUOC_GIAChanging(string value);
    partial void OnTEN_QUOC_GIAChanged();
    partial void OnGHI_CHUChanging(string value);
    partial void OnGHI_CHUChanged();
    #endregion
		
		public QUOC_GIA()
		{
			this._KHACH_HANGs = new EntitySet<KHACH_HANG>(new Action<KHACH_HANG>(this.attach_KHACH_HANGs), new Action<KHACH_HANG>(this.detach_KHACH_HANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_QUOC_GIA", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_QUOC_GIA
		{
			get
			{
				return this._MA_QUOC_GIA;
			}
			set
			{
				if ((this._MA_QUOC_GIA != value))
				{
					this.OnMA_QUOC_GIAChanging(value);
					this.SendPropertyChanging();
					this._MA_QUOC_GIA = value;
					this.SendPropertyChanged("MA_QUOC_GIA");
					this.OnMA_QUOC_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_QUOC_GIA", DbType="NVarChar(250)")]
		public string TEN_QUOC_GIA
		{
			get
			{
				return this._TEN_QUOC_GIA;
			}
			set
			{
				if ((this._TEN_QUOC_GIA != value))
				{
					this.OnTEN_QUOC_GIAChanging(value);
					this.SendPropertyChanging();
					this._TEN_QUOC_GIA = value;
					this.SendPropertyChanged("TEN_QUOC_GIA");
					this.OnTEN_QUOC_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(250)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this.OnGHI_CHUChanging(value);
					this.SendPropertyChanging();
					this._GHI_CHU = value;
					this.SendPropertyChanged("GHI_CHU");
					this.OnGHI_CHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QUOC_GIA_KHACH_HANG", Storage="_KHACH_HANGs", ThisKey="MA_QUOC_GIA", OtherKey="MA_QUOC_GIA")]
		public EntitySet<KHACH_HANG> KHACH_HANGs
		{
			get
			{
				return this._KHACH_HANGs;
			}
			set
			{
				this._KHACH_HANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACH_HANGs(KHACH_HANG entity)
		{
			this.SendPropertyChanging();
			entity.QUOC_GIA = this;
		}
		
		private void detach_KHACH_HANGs(KHACH_HANG entity)
		{
			this.SendPropertyChanging();
			entity.QUOC_GIA = null;
		}
	}
}
#pragma warning restore 1591
